"""
Maximum AND Value
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.

Input:
The first line of the input contains a single integer T, denoting the number of test cases. Then T test cases follow. Each test-case has two lines of the input, the first line contains an integer denoting the size of an array N and the second line of input contains N positive integers

Output:
For each testcase, print Maximum AND Value of a pair in a separate line.

User Task:
The task is to complete the function maxAND() which takes the array elements and N (size of array) and input and returns the maximum AND value generated by any pair in the array.

Constraints:
1 <=T <= 100
1 <= N <= 100
1 <= arr[i] <= 104

Example:
Input:
2
4
4 8 12 16
4
4 8 16 2

Output:
8
0

Explanation:
Testcase 1: Pair (8,12) has the Maximum AND Value  i.e. 8.
Testcase 2: Maximum AND Value is 0.

 

** For More Input/Output Examples Use 'Expected Output' option **
"""
def maxAND(arr,n):
    l1 = []
    for i in range(32, 0, -1):
        a = 1<<(i-1)
        l = [w for w in arr if w&a != 0]
        if(len(l) >=2 ):
            l1.append(i)
            arr = l
    v=0
    for k in l1:
        v=v+2**(k-1)
    return v
assert maxAND([4,8,12,16],4) == 8
assert maxAND([4,8,16,2],4) == 0

print('The code ran Correctly')
